### ISSUE TITLE
BGP ASN not getting set/picked

### ISSUE THREAD

**Issue by hoodbu** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit-peering#3] opened 2021-02-05 23:53 UTC
After upgrading from Controller 6.2 (and TF 0.12) to Controller 6.3 (and TF 0.13), the same code breaks with this message:

```
module.transit-peering.aviatrix_transit_gateway_peering.peering["ace-gcp-us-east1-transit1:ace-azure-east-us-transit1"]: Creating...
module.transit-peering.aviatrix_transit_gateway_peering.peering["ace-gcp-us-east1-transit1:ace-aws-eu-west-1-transit1"]: Creating...
module.transit-peering.aviatrix_transit_gateway_peering.peering["ace-azure-east-us-transit1:ace-aws-eu-west-1-transit1"]: Creating...

Error: failed to create Aviatrix Transit Gateway peering: rest API create_inter_transit_gateway_peering Post failed: [AVXERR-TRANSIT-0168] Transit gateway ace-gcp-us-east1-transit1 and ace-aws-eu-west-1-transit1 has the same ASN number None. This is not allowed in Activemesh 2.0 in transit peering.



Error: failed to create Aviatrix Transit Gateway peering: rest API create_inter_transit_gateway_peering Post failed: [AVXERR-TRANSIT-0168] Transit gateway ace-gcp-us-east1-transit1 and ace-azure-east-us-transit1 has the same ASN number None. This is not allowed in Activemesh 2.0 in transit peering.



Error: failed to create Aviatrix Transit Gateway peering: rest API create_inter_transit_gateway_peering Post failed: [AVXERR-TRANSIT-0168] Transit gateway ace-azure-east-us-transit1 and ace-aws-eu-west-1-transit1 has the same ASN number None. This is not allowed in Activemesh 2.0 in transit peering.
```
I don't trust these messages. This worked fine before the upgrade. The code is [here](https://github.com/hoodbu/ace-cloud-ops/). It just uses modules **aws-transit-firenet**, **gcp-transit**, and **azure-transit** to build the transits, and then peers them with this module **mc-transit-peering**. Either the transit modules aren't setting BGP ASN or the mc-transit-peering module isn't reading it properly.

**Comment by Dennizz** [comment] 2021-02-08 15:45
The issue is on the transit GW side of things, not on the peering resource. As such this needs to be addressed by the transit modules. As this is new behavior of 6.3, it will be integrated in newer transit module versions.

**Closed as completed by Dennizz** 2021-02-08 15:45 UTC
